<x-layouts.app>
    <div class="max-w-2xl mx-auto bg-white border rounded-lg shadow-sm p-6">
        <h1 class="text-lg font-semibold mb-4">Create automation</h1>

        <form method="POST" action="{{ route('automations.store', $company) }}" class="space-y-4">
            @csrf

            <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Name</label>
                <input type="text"
                       name="name"
                       value="{{ old('name') }}"
                       class="w-full border-gray-300 rounded-md text-sm">
                @error('name')
                    <p class="text-[11px] text-red-600 mt-1">{{ $message }}</p>
                @enderror
            </div>

            <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Trigger</label>
                <select name="trigger"
                        class="w-full border-gray-300 rounded-md text-sm">
                    <option value="">Select trigger</option>
                    <option value="cod_order" {{ old('trigger') === 'cod_order' ? 'selected' : '' }}>COD order created</option>
                    <option value="abandoned_cart" {{ old('trigger') === 'abandoned_cart' ? 'selected' : '' }}>Abandoned checkout</option>
                    <option value="order_fulfilled" {{ old('trigger') === 'order_fulfilled' ? 'selected' : '' }}>Order fulfilled</option>
                </select>
                @error('trigger')
                    <p class="text-[11px] text-red-600 mt-1">{{ $message }}</p>
                @enderror
            </div>

            <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">
                    Flow definition (JSON) – temporary until drag & drop builder
                </label>
<textarea name="flow_definition"
          rows="8"
          class="w-full border-gray-300 rounded-md text-xs"
          placeholder='{
  "steps": [
    {
      "type": "simple_text",
      "config": {
        "text": "Hi @{{ customer_name }}, your COD order @{{ order_id }} of ₹@{{ order_total }} is received."
      }
    }
  ]
}'>{{ old('flow_definition') }}</textarea>

                @error('flow_definition')
                    <p class="text-[11px] text-red-600 mt-1">{{ $message }}</p>
                @enderror
                <p class="text-[11px] text-gray-400 mt-1">
                    Keep valid JSON. Later this will be generated by visual builder.
                </p>
            </div>

            <div class="flex justify-end">
                <a href="{{ route('automations.index', $company) }}"
                   class="px-3 py-2 text-xs rounded-md border border-gray-300 text-gray-600 hover:bg-gray-50 mr-2">
                    Cancel
                </a>
                <button type="submit"
                        class="px-4 py-2 text-xs rounded-md bg-indigo-600 text-white font-semibold hover:bg-indigo-700">
                    Save automation
                </button>
            </div>
        </form>
    </div>
</x-layouts.app>
